[build]
  functions = "netlify/functions"
  publish = "dist/public"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  port = 8888
  publish = "dist/public"
  functions = "netlify/functions"
